org: fnlog0
app: test
service: log-pipe-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_DB_URI: ${env:MONGO_DB_URI}
    SES_AWS_ACCESS_KEY_ID: ${env:SES_AWS_ACCESS_KEY_ID}
    SES_AWS_SECRET_ACCESS_KEY: ${env:SES_AWS_SECRET_ACCESS_KEY}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    JWT_REFRESH_SECRET_KEY: ${env:JWT_REFRESH_SECRET_KEY}

functions:
  graphql:
    handler: src/lambda.graphqlHandler
    memorySize: 1024
    timeout: 60
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  individually: true

custom:
  build:
    esbuild:
      bundle: true
      minify: true
      sourcemap: true
      target: node14
      platform: node
      external:
        - aws-sdk
